server:
  port: 7001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: route-fare-management-service
  datasource:
    url: jdbc:postgresql://localhost:5432/gocashless_rfms_db
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # 'update' for development, 'none' or 'validate' for production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



