package com.gocashless.pps.dto;

import lombok.Data;
import java.math.BigDecimal;
import java.util.UUID;

/**
 * DTO representing the decrypted payload from the QR code,
 * sent by the Passenger App to PPS to initiate payment.
 */
@Data
public class InitiatePaymentRequest {
    private UUID conductorId;
    private String passengerPhoneNumber; // This would be the passenger's phone number from their app/profile
    private BigDecimal amount;
    private String currency;
    private String transactionRef; // The unique ID generated by QRGS
    // Add passengerId if available from UMS
    private UUID passengerId;
}
