server:
  port: 7002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka # Unique port for QRGS, e.g., 8082

spring:
  application:
    name: qr-code-generation-service # Name for Eureka registration



# QR Code Configuration (optional, for default size/color)
qrcode:
  width: 300
  height: 300
  format: PNG
  charset: UTF-8

# Encryption secret for QR payload (for testing, use a simple one)
qr:
  encryption:
    secret-key: aVerySimpleTestSecretKeyForQrEncryption
