server:
  port: 7000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: user-management-service

# PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/gocashless_ums_db
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Use 'create' or 'create-drop' for development, 'none' or 'validate' for production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Secret (VERY IMPORTANT: Use a strong, securely stored secret in production)
jwt:
  secret: yourSuperSecretKeyForJWTTokenGenerationAndValidationWhichShouldBeLongAndComplex
  expiration: 3600000 # 1 hour in milliseconds
