server:
  port: 7000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: user-management-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/gocashless_ums_db
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Use 'create' or 'create-drop' for development, 'none' or 'validate' for production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Secret (VERY IMPORTANT: Use a strong, securely stored secret in production)
jwt:
  secret: 4125442A472D4B6150645367566B5970337336763979244226452948404D6351
  expiration: 86400000 # 24 hours in milliseconds
